system: Remove CPU
This has a None value that breaks the prometheus exporter with

```
    k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(mktxp_system_uptime, Time interval since boot-up, gauge, , [Sample(name='mktxp_system_uptime', labels={'version': '7.1.1 (stable)', 'board_name': 'CCR2116-12G-4S+', 'cpu': None, 'architecture_name': 'arm64', 'routerboard_name': 'router-devops', 'routerboard_address': '192.168.88.1'}, value=175526.0, timestamp=None, exemplar=None)]))
----------------------------------------

```